"""tables

Revision ID: 59ef70ca9aa0
Revises: 110a305780a1
Create Date: 2020-12-04 06:50:49.430285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59ef70ca9aa0'
down_revision = '110a305780a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('children',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('term', sa.String(length=50), nullable=False),
    sa.Column('isPayed', sa.Boolean(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('instuctor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instuctor_id'], ['instructors.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['adults.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['adults.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('families',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['adults.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('charges', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('invoiceId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['invoiceId'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pieces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('composer', sa.String(length=50), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('resource_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resource_type_id'], ['resource_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_assigned', sa.Date(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('piece_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], ),
    sa.ForeignKeyConstraint(['piece_id'], ['pieces.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['adults.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lesson_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('badge', sa.Boolean(), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('piece_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['piece_id'], ['pieces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lesson_tasks')
    op.drop_table('assignments')
    op.drop_table('resources')
    op.drop_table('pieces')
    op.drop_table('invoice_items')
    op.drop_table('families')
    op.drop_table('resource_types')
    op.drop_table('lessons')
    op.drop_table('invoices')
    op.drop_table('children')
    op.drop_table('books')
    op.drop_table('assignment_types')
    # ### end Alembic commands ###
