"""empty message

Revision ID: 195cb2da08b9
Revises: c0d6eef1ee92
Create Date: 2020-12-10 08:51:46.007276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '195cb2da08b9'
down_revision = 'c0d6eef1ee92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'rate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('rate', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
